import {useEffect,useState} from 'preact/hooks';
import {REPORT_CATEGORIES,type CommunityView} from '@shared/community';
import {SOCIAL_PAGE_SIZE} from '@shared/social';
import {ui,useUI,togglePanel} from '../store';
import {PanelFrame,Tabs} from './common';
import {cmd} from '../../net/api';
import {openInspection} from './inspect';

export function reportMessage(name:string,message:string){ui.set({reportContext:{name,message}});togglePanel('community',true);}
export function CommunityPanel(){
  const context=useUI(s=>s.reportContext),me=useUI(s=>s.char?.name),[tab,setTab]=useState<'guild'|'invites'|'reports'|'rules'>(context?'reports':'guild'),[data,setData]=useState<CommunityView|null>(null),[name,setName]=useState(context?.name??''),[message,setMessage]=useState(context?.message??''),[text,setText]=useState(''),[category,setCategory]=useState<string>('harassment'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[page,setPage]=useState(0);
  const refresh=async()=>{const r=await cmd<CommunityView>('community',{action:'view'});if(r.ok&&r.data)setData(r.data);else setNotice(r.err??'Could not load community');};
  useEffect(()=>{void refresh();},[]);
  useEffect(()=>{if(context){setTab('reports');setName(context.name);setMessage(context.message);setPage(0);}},[context]);
  const act=async(action:string,args:Record<string,unknown>={})=>{setBusy(true);setNotice('');try{const r=await cmd('community',{action,...args});setNotice(r.ok?action==='report'?'Report saved for owner review. No automatic punishment.':'Saved.':r.err??'Action failed');if(r.ok){if(action==='report'){setMessage('');ui.set({reportContext:null});}setText('');await refresh();}}finally{setBusy(false);}};
  const guild=data?.guild,rank=guild?.rank,entries=tab==='guild'?(guild?.members??[]):tab==='reports'?(data?.reports??[]):[],pages=Math.max(1,Math.ceil(entries.length/SOCIAL_PAGE_SIZE)),current=Math.min(page,pages-1);
  return <PanelFrame id="community" title="Guild & reports" width={1000} sub={guild?.name??'Companions and community care'}>
    <Tabs tabs={[{id:'guild',label:'Guild'},{id:'invites',label:'Invitations',badge:data?.invites.length},{id:'reports',label:'Reports'},{id:'rules',label:'Rules'}]} value={tab} onChange={v=>{setTab(v);setPage(0);setText('');}}/>
    <button class="btn tiny" disabled={busy} onClick={()=>void refresh()}>Refresh</button>{notice&&<p role="status" class="pn-note">{notice}</p>}
    {tab==='guild'?(guild?<>
      <p class="pn-note">{guild.motd||'No message of the day.'}</p>
      <div class="social-list">{guild.members.slice(current*8,(current+1)*8).map(m=><div class="social-row" key={m.name}><div><strong>{m.name} · {m.rank}</strong><span>{m.online?'Online':'Unavailable'}</span></div><button class="btn tiny" onClick={()=>openInspection(m.name)}>Inspect</button>{m.name!==me&&rank==='leader'&&<><button class="btn tiny" disabled={busy} onClick={()=>void act(m.rank==='officer'?'demote':'promote',{name:m.name})}>{m.rank==='officer'?'Demote':'Promote'}</button><button class="btn tiny" disabled={busy} onClick={()=>void act('leader',{name:m.name})}>Make leader</button></>}{m.name!==me&&(rank==='leader'||rank==='officer'&&m.rank==='member')&&<button class="btn tiny" disabled={busy} onClick={()=>void act('kick',{name:m.name})}>Remove</button>}</div>)}</div>
      {rank!=='member'&&<><form class="party-invite" onSubmit={e=>{e.preventDefault();void act('invite',{name:name.trim()});}}><label>Online character name<input value={name} maxLength={16} onInput={e=>setName(e.currentTarget.value)}/></label><button class="btn" disabled={busy||!name.trim()}>Invite to guild</button></form><form class="party-invite" onSubmit={e=>{e.preventDefault();void act('motd',{text});}}><label>New message of the day (200 characters)<input value={text} maxLength={200} onInput={e=>setText(e.currentTarget.value)}/></label><button class="btn" disabled={busy}>Save message</button></form></>}
      <div class="social-options"><button class="btn" onClick={()=>{togglePanel('community',false);ui.set({chatChannel:'guild',chatOpen:true});}}>Guild chat</button><button class="btn" disabled={busy} onClick={()=>void act('leave')}>Leave guild</button></div><p class="pn-note">One guild per character, 80 members. Leaders transfer leadership before leaving a populated guild. No bank, currency costs or combat bonuses.</p>
    </>:<><p>Create a guild, or ask an officer for an invitation.</p><form class="party-invite" onSubmit={e=>{e.preventDefault();void act('create',{name:name.trim()});}}><label>Guild name (3–32 letters, numbers or spaces)<input value={name} maxLength={32} onInput={e=>setName(e.currentTarget.value)}/></label><button class="btn" disabled={busy||!name.trim()}>Create guild</button></form></>):tab==='invites'?<>
      <p class="pn-note">Invitations expire after 60 seconds. Refresh to see new invitations.</p>{!data?.invites.length&&<p>No pending guild invitations.</p>}{data?.invites.map(i=><div class="social-row" key={i.id}><div><strong>{i.guild}</strong><span>Invited by {i.from}</span></div><button class="btn" disabled={busy||!!guild} onClick={()=>void act('accept',{invite:i.id})}>Accept</button><button class="btn" disabled={busy} onClick={()=>void act('decline',{invite:i.id})}>Decline</button></div>)}
    </>:tab==='reports'?<>
      <p class="pn-note">Reports go to the owner for manual review and expire after 30 days. Describe what happened; a report is not proof or an automatic punishment.</p>
      <form onSubmit={e=>{e.preventDefault();void act('report',{name:name.trim(),category,text,...(message?{message}:{})});}}><div class="party-invite"><label>Character name<input value={name} maxLength={16} onInput={e=>{setName(e.currentTarget.value);setMessage('');}}/></label></div><div class="social-options">{REPORT_CATEGORIES.map(c=><button type="button" class={`btn tiny${category===c?' primary':''}`} onClick={()=>setCategory(c)}>{c}</button>)}</div><div class="party-invite"><label>What happened? (200 characters)<input value={text} maxLength={200} onInput={e=>setText(e.currentTarget.value)}/></label><button class="btn" disabled={busy||!name.trim()||(!text.trim()&&!message)}>Submit report</button></div>{message&&<p class="pn-note">The selected message you received will be attached. <button type="button" class="btn tiny" onClick={()=>setMessage('')}>Remove attachment</button></p>}</form>
      <div class="social-list">{data?.reports.slice(current*8,(current+1)*8).map(r=><div class="social-row" key={r.id}><div><strong>{r.target} · {r.category}</strong><span>{new Date(r.at).toLocaleDateString()} · {r.resolved?'Reviewed':'Pending owner review'} · {r.id.slice(0,8)}</span></div></div>)}</div>
    </>:<><h3>Community rules</h3><p>Respect other players. Do not harass, threaten, impersonate or spam. Do not cheat, exploit or advertise real-money trades. Report concerns with accurate descriptions; do not submit knowingly false reports.</p><p>Use Social to block messages and invitations or mute chat. Leave a party if you no longer want to share its frames. The owner reviews reports and can mute or suspend a character manually. Contact the owner to request a review of a decision.</p><p>Ordinary chat stays in server memory only. A report may retain the selected received message and your description for 30 days. Expiry runs when the server is running; it runs again at startup. Active sanctions remain until lifted or expired. These controls currently apply to characters, pending account authentication.</p><p>Links and owner-configured phrases may be rejected by the text filter. Filter matches do not cause automatic punishment.</p></>}
    {(tab==='guild'&&guild||tab==='reports')&&<div class="social-pages"><button class="btn tiny" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>{current+1} / {pages}</span><button class="btn tiny" disabled={current===pages-1} onClick={()=>setPage(current+1)}>Next</button></div>}
  </PanelFrame>;
}
